parameters:
    pim_catalog.normalizer.indexing_product.product.class: Pim\Component\Catalog\Normalizer\Indexing\ProductFormat\ProductNormalizer
    pim_catalog.normalizer.indexing_product.product.properties.class: Pim\Component\Catalog\Normalizer\Indexing\ProductFormat\PropertiesNormalizer
    pim_catalog.normalizer.indexing_product.product.family.class: Pim\Component\Catalog\Normalizer\Indexing\FamilyNormalizer
    pim_catalog.normalizer.indexing_product.datetime.class: Pim\Component\Catalog\Normalizer\Indexing\DateTimeNormalizer
    pim_catalog.normalizer.indexing_product.product.product_value_collection.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\ProductValueCollectionNormalizer
    pim_catalog.normalizer.indexing_product.product.completeness_collection.class: Pim\Component\Catalog\Normalizer\Indexing\ProductFormat\CompletenessCollectionNormalizer
    pim_catalog.normalizer.indexing_product.product.number.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\NumberNormalizer
    pim_catalog.normalizer.indexing_product.product.option.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\OptionNormalizer
    pim_catalog.normalizer.indexing_product.product.options.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\OptionsNormalizer
    pim_catalog.normalizer.indexing_product.product.dummy.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\DummyNormalizer
    pim_catalog.normalizer.indexing_product.date.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\DateNormalizer
    pim_catalog.normalizer.indexing_product.product.text.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\TextNormalizer
    pim_catalog.normalizer.indexing_product.product.text_area.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\TextAreaNormalizer
    pim_catalog.normalizer.indexing_product.product.price_collection.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\PriceCollectionNormalizer
    pim_catalog.normalizer.indexing_product.product.metric.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\MetricNormalizer
    pim_catalog.normalizer.indexing_product.product.media.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\MediaNormalizer
    pim_catalog.normalizer.indexing_product.product.boolean.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\BooleanNormalizer

    pim_catalog.normalizer.indexing_product_and_product_model.product.class: Pim\Component\Catalog\Normalizer\Indexing\ProductAndProductModelFormat\ProductModelNormalizer
    pim_catalog.normalizer.indexing_product_and_product_model.product.properties.class: Pim\Component\Catalog\Normalizer\Indexing\ProductAndProductModelFormat\ProductPropertiesNormalizer

    pim_catalog.normalizer.indexing_product_and_product_model.product_model.class: Pim\Component\Catalog\Normalizer\Indexing\ProductAndProductModelFormat\ProductModelNormalizer
    pim_catalog.normalizer.indexing_product_and_product_model.product_model.properties.class: Pim\Component\Catalog\Normalizer\Indexing\ProductAndProductModelFormat\ProductModelPropertiesNormalizer

services:
    pim_catalog.normalizer.indexing_product.product:
        class: '%pim_catalog.normalizer.indexing_product.product.class%'
        arguments:
            - '@pim_catalog.normalizer.indexing_product.product.properties'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.properties:
        class: '%pim_catalog.normalizer.indexing_product.product.properties.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }

    pim_catalog.normalizer.indexing_product.datetime:
        class: '%pim_catalog.normalizer.indexing_product.datetime.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.datetime'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.family:
        class: '%pim_catalog.normalizer.indexing_product.product.family.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.repository.locale'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.product_value_collection:
        class: '%pim_catalog.normalizer.indexing_product.product.product_value_collection.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.completeness_collection:
        class: '%pim_catalog.normalizer.indexing_product.product.completeness_collection.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.number:
        class: '%pim_catalog.normalizer.indexing_product.product.number.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.options:
        class: '%pim_catalog.normalizer.indexing_product.product.options.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.dummy:
        class: '%pim_catalog.normalizer.indexing_product.product.dummy.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 80 }

    pim_catalog.normalizer.indexing_product.date:
        class: '%pim_catalog.normalizer.indexing_product.date.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_catalog.normalizer.indexing_product.product.text:
        class: '%pim_catalog.normalizer.indexing_product.product.text.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.text_area:
        class: '%pim_catalog.normalizer.indexing_product.product.text_area.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.option:
        class: '%pim_catalog.normalizer.indexing_product.product.option.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.price_collection:
        class: '%pim_catalog.normalizer.indexing_product.product.price_collection.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product.product_value'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.metric:
        class: '%pim_catalog.normalizer.indexing_product.product.metric.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.media:
        class: '%pim_catalog.normalizer.indexing_product.product.media.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product.product.boolean:
        class: '%pim_catalog.normalizer.indexing_product.product.boolean.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product_and_product_model.product_model:
        class: '%pim_catalog.normalizer.indexing_product_and_product_model.product_model.class%'
        arguments:
            - '@pim_catalog.normalizer.indexing_product_and_product_model.product_model.properties'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product_and_product_model.product_model.properties:
        class: '%pim_catalog.normalizer.indexing_product_and_product_model.product_model.properties.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }

    pim_catalog.normalizer.indexing_product_and_product_model.product:
        class: '%pim_catalog.normalizer.indexing_product_and_product_model.product.class%'
        arguments:
            - '@pim_catalog.normalizer.indexing_product_and_product_model.product.properties'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing_product_and_product_model.product.properties:
        class: '%pim_catalog.normalizer.indexing_product_and_product_model.product.properties.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }


