parameters:
    pim_catalog.normalizer.indexing.product.class: Pim\Component\Catalog\Normalizer\Indexing\Product\ProductNormalizer
    pim_catalog.normalizer.indexing.product.properties.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\PropertiesNormalizer
    pim_catalog.normalizer.indexing.product.family.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\FamilyNormalizer
    pim_catalog.normalizer.indexing.datetime.class: Pim\Component\Catalog\Normalizer\Indexing\DateTimeNormalizer
    pim_catalog.normalizer.indexing.product.product_value_collection.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\ProductValueCollectionNormalizer
    pim_catalog.normalizer.indexing.product.completeness_collection.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\CompletenessCollectionNormalizer
    pim_catalog.normalizer.indexing.product.number.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\NumberNormalizer
    pim_catalog.normalizer.indexing.product.option.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\OptionNormalizer
    pim_catalog.normalizer.indexing.product.options.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\OptionsNormalizer
    pim_catalog.normalizer.indexing.product.dummy.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\DummyNormalizer
    pim_catalog.normalizer.indexing.date.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\DateNormalizer
    pim_catalog.normalizer.indexing.product.text.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\TextNormalizer
    pim_catalog.normalizer.indexing.product.text_area.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\TextAreaNormalizer
    pim_catalog.normalizer.indexing.product.price_collection.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\PriceCollectionNormalizer
    pim_catalog.normalizer.indexing.product.metric.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\MetricNormalizer
    pim_catalog.normalizer.indexing.product.media.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\MediaNormalizer
    pim_catalog.normalizer.indexing.product.boolean.class: Pim\Component\Catalog\Normalizer\Indexing\ProductValue\BooleanNormalizer

services:
    pim_catalog.normalizer.indexing.product:
        class: '%pim_catalog.normalizer.indexing.product.class%'
        arguments:
            - '@pim_catalog.normalizer.indexing.product.properties'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.properties:
        class: '%pim_catalog.normalizer.indexing.product.properties.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }

    pim_catalog.normalizer.indexing.datetime:
        class: '%pim_catalog.normalizer.indexing.datetime.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.datetime'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.family:
        class: '%pim_catalog.normalizer.indexing.product.family.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.repository.locale'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.product_value_collection:
        class: '%pim_catalog.normalizer.indexing.product.product_value_collection.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.completeness_collection:
        class: '%pim_catalog.normalizer.indexing.product.completeness_collection.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.number:
        class: '%pim_catalog.normalizer.indexing.product.number.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.options:
        class: '%pim_catalog.normalizer.indexing.product.options.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.dummy:
        class: '%pim_catalog.normalizer.indexing.product.dummy.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 80 }

    pim_catalog.normalizer.indexing.date:
        class: '%pim_catalog.normalizer.indexing.date.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_catalog.normalizer.indexing.product.text:
        class: '%pim_catalog.normalizer.indexing.product.text.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.text_area:
        class: '%pim_catalog.normalizer.indexing.product.text_area.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.option:
        class: '%pim_catalog.normalizer.indexing.product.option.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.price_collection:
        class: '%pim_catalog.normalizer.indexing.product.price_collection.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product.product_value'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.metric:
        class: '%pim_catalog.normalizer.indexing.product.metric.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.media:
        class: '%pim_catalog.normalizer.indexing.product.media.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.boolean:
        class: '%pim_catalog.normalizer.indexing.product.boolean.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
